export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const ADD_USER = "ADD_USER";
export const CREATE_SESSION = "CREATE_SESSION";
export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const DESTROY_SESSION = "DESTROY_SESSION";